server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://115.175.45.173:5432/deeptalk?characterEncoding=UTF-8&useUnicode=true
    username: postgres
    password: DeepTalk@2024
    driver-class-name: org.postgresql.Driver
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        connection:
          characterEncoding: UTF-8
        jdbc:
          useUnicode: true
          characterEncoding: UTF-8
  mail:
    host: smtp.qq.com
    port: 587
    username: 1602113776@qq.com  # 替换为您的QQ邮箱
    password: jhxxemecrsgjhhca    # 替换为您的QQ邮箱授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwt:
  expiration:
    normal: 86400000  # 24小时
    remember-me: 2592000000  # 30天

kurento:
  client:
    kms:
      ws:
        uri: ws://127.0.0.1:8888/kurento